// Mocks generated by Mockito 5.4.6 from annotations
// in pomer/test/timer_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pomer/core/services/audio_service.dart' as _i2;
import 'package:pomer/core/services/foreground_service.dart' as _i5;
import 'package:pomer/core/services/notification_service.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AudioService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioService extends _i1.Mock implements _i2.AudioService {
  MockAudioService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> playAlarm({
    String? alarmAssetPath = 'assets/audio/alarm_x1.ogg',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #playAlarm,
          [],
          {
            #alarmAssetPath: alarmAssetPath,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> stopAlarm() => (super.noSuchMethod(
        Invocation.method(
          #stopAlarm,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> playAmbient({required String? ambientAssetPath}) =>
      (super.noSuchMethod(
        Invocation.method(
          #playAmbient,
          [],
          {
            #ambientAssetPath: ambientAssetPath,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> stopAmbient() => (super.noSuchMethod(
        Invocation.method(
          #stopAmbient,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> transitionAmbient({
    required String? ambientAssetPath,
    Duration? transitionDuration = const Duration(seconds: 2),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #transitionAmbient,
          [],
          {
            #ambientAssetPath: ambientAssetPath,
            #transitionDuration: transitionDuration,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i4.NotificationService {
  MockNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> requestPermissions() => (super.noSuchMethod(
        Invocation.method(
          #requestPermissions,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> showNotification({
    required int? id,
    required String? title,
    required String? body,
    bool? playSound = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showNotification,
          [],
          {
            #id: id,
            #title: title,
            #body: body,
            #playSound: playSound,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> cancelNotification(int? id) => (super.noSuchMethod(
        Invocation.method(
          #cancelNotification,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> cancelAllNotifications() => (super.noSuchMethod(
        Invocation.method(
          #cancelAllNotifications,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [ForegroundService].
///
/// See the documentation for Mockito's code generation for more information.
class MockForegroundService extends _i1.Mock implements _i5.ForegroundService {
  MockForegroundService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void init() => super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void registerActionCallback(void Function(String)? onAction) =>
      super.noSuchMethod(
        Invocation.method(
          #registerActionCallback,
          [onAction],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<void> startService(
    String? title,
    String? text, {
    bool? isPaused = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #startService,
          [
            title,
            text,
          ],
          {#isPaused: isPaused},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateService(
    String? title,
    String? text, {
    bool? isPaused = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateService,
          [
            title,
            text,
          ],
          {#isPaused: isPaused},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> stopService() => (super.noSuchMethod(
        Invocation.method(
          #stopService,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
