// Mocks generated by Mockito 5.4.6 from annotations
// in pomer/test/helpers/mock_services.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:pomer/core/services/audio_service.dart' as _i2;
import 'package:pomer/core/services/battery_optimization_service.dart' as _i7;
import 'package:pomer/core/services/foreground_service.dart' as _i5;
import 'package:pomer/core/services/notification_service.dart' as _i4;
import 'package:pomer/core/services/power_management_service.dart' as _i6;
import 'package:pomer/features/statistics/services/csv_export_service.dart'
    as _i9;
import 'package:shared_preferences/src/shared_preferences_async.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AudioService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioService extends _i1.Mock implements _i2.AudioService {
  @override
  _i3.Future<void> playAlarm(
          {String? alarmAssetPath = 'assets/audio/alarm_x1.ogg'}) =>
      (super.noSuchMethod(
        Invocation.method(
          #playAlarm,
          [],
          {#alarmAssetPath: alarmAssetPath},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> stopAlarm() => (super.noSuchMethod(
        Invocation.method(
          #stopAlarm,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> playAmbient({required String? ambientAssetPath}) =>
      (super.noSuchMethod(
        Invocation.method(
          #playAmbient,
          [],
          {#ambientAssetPath: ambientAssetPath},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> stopAmbient() => (super.noSuchMethod(
        Invocation.method(
          #stopAmbient,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> transitionAmbient({
    required String? ambientAssetPath,
    Duration? transitionDuration = const Duration(seconds: 2),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #transitionAmbient,
          [],
          {
            #ambientAssetPath: ambientAssetPath,
            #transitionDuration: transitionDuration,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i4.NotificationService {
  @override
  _i3.Future<void> requestPermissions() => (super.noSuchMethod(
        Invocation.method(
          #requestPermissions,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> showNotification({
    required int? id,
    required String? title,
    required String? body,
    bool? playSound = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showNotification,
          [],
          {
            #id: id,
            #title: title,
            #body: body,
            #playSound: playSound,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> cancelNotification(int? id) => (super.noSuchMethod(
        Invocation.method(
          #cancelNotification,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> cancelAllNotifications() => (super.noSuchMethod(
        Invocation.method(
          #cancelAllNotifications,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [ForegroundService].
///
/// See the documentation for Mockito's code generation for more information.
class MockForegroundService extends _i1.Mock implements _i5.ForegroundService {
  @override
  void init() => super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void registerActionCallback(void Function(String)? onAction) =>
      super.noSuchMethod(
        Invocation.method(
          #registerActionCallback,
          [onAction],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<void> startService(
    String? title,
    String? text, {
    bool? isPaused = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #startService,
          [
            title,
            text,
          ],
          {#isPaused: isPaused},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateService(
    String? title,
    String? text, {
    bool? isPaused = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateService,
          [
            title,
            text,
          ],
          {#isPaused: isPaused},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> stopService() => (super.noSuchMethod(
        Invocation.method(
          #stopService,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [PowerManagementService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPowerManagementService extends _i1.Mock
    implements _i6.PowerManagementService {
  @override
  bool get isWakeLockHeld => (super.noSuchMethod(
        Invocation.getter(#isWakeLockHeld),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i3.Future<void> acquireForTimer() => (super.noSuchMethod(
        Invocation.method(
          #acquireForTimer,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> releaseWhenIdle() => (super.noSuchMethod(
        Invocation.method(
          #releaseWhenIdle,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void updateScreenState(bool? isScreenOn) => super.noSuchMethod(
        Invocation.method(
          #updateScreenState,
          [isScreenOn],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<void> syncWithTimerState(bool? isRunning) => (super.noSuchMethod(
        Invocation.method(
          #syncWithTimerState,
          [isRunning],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [BatteryOptimizationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBatteryOptimizationService extends _i1.Mock
    implements _i7.BatteryOptimizationService {
  @override
  _i3.Future<bool?> isBatteryOptimized() => (super.noSuchMethod(
        Invocation.method(
          #isBatteryOptimized,
          [],
        ),
        returnValue: _i3.Future<bool?>.value(),
        returnValueForMissingStub: _i3.Future<bool?>.value(),
      ) as _i3.Future<bool?>);

  @override
  _i3.Future<bool> isIgnoringBatteryOptimizations() => (super.noSuchMethod(
        Invocation.method(
          #isIgnoringBatteryOptimizations,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> logBatteryOptimizationStatus() => (super.noSuchMethod(
        Invocation.method(
          #logBatteryOptimizationStatus,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void updateStatus(bool? isOptimized) => super.noSuchMethod(
        Invocation.method(
          #updateStatus,
          [isOptimized],
        ),
        returnValueForMissingStub: null,
      );

  @override
  String getUserEducationMessage() => (super.noSuchMethod(
        Invocation.method(
          #getUserEducationMessage,
          [],
        ),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #getUserEducationMessage,
            [],
          ),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #getUserEducationMessage,
            [],
          ),
        ),
      ) as String);
}

/// A class which mocks [CsvExportService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCsvExportService extends _i1.Mock implements _i9.CsvExportService {
  @override
  _i3.Future<void> exportSessions() => (super.noSuchMethod(
        Invocation.method(
          #exportSessions,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [SharedPreferencesAsync].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: must_be_immutable
class MockSharedPreferencesAsync extends _i1.Mock
    implements _i10.SharedPreferencesAsync {
  @override
  _i3.Future<Set<String>> getKeys({Set<String>? allowList}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getKeys,
          [],
          {#allowList: allowList},
        ),
        returnValue: _i3.Future<Set<String>>.value(<String>{}),
        returnValueForMissingStub: _i3.Future<Set<String>>.value(<String>{}),
      ) as _i3.Future<Set<String>>);

  @override
  _i3.Future<Map<String, Object?>> getAll({Set<String>? allowList}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
          {#allowList: allowList},
        ),
        returnValue:
            _i3.Future<Map<String, Object?>>.value(<String, Object?>{}),
        returnValueForMissingStub:
            _i3.Future<Map<String, Object?>>.value(<String, Object?>{}),
      ) as _i3.Future<Map<String, Object?>>);

  @override
  _i3.Future<bool?> getBool(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getBool,
          [key],
        ),
        returnValue: _i3.Future<bool?>.value(),
        returnValueForMissingStub: _i3.Future<bool?>.value(),
      ) as _i3.Future<bool?>);

  @override
  _i3.Future<int?> getInt(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getInt,
          [key],
        ),
        returnValue: _i3.Future<int?>.value(),
        returnValueForMissingStub: _i3.Future<int?>.value(),
      ) as _i3.Future<int?>);

  @override
  _i3.Future<double?> getDouble(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getDouble,
          [key],
        ),
        returnValue: _i3.Future<double?>.value(),
        returnValueForMissingStub: _i3.Future<double?>.value(),
      ) as _i3.Future<double?>);

  @override
  _i3.Future<String?> getString(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getString,
          [key],
        ),
        returnValue: _i3.Future<String?>.value(),
        returnValueForMissingStub: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<List<String>?> getStringList(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getStringList,
          [key],
        ),
        returnValue: _i3.Future<List<String>?>.value(),
        returnValueForMissingStub: _i3.Future<List<String>?>.value(),
      ) as _i3.Future<List<String>?>);

  @override
  _i3.Future<bool> containsKey(String? key) => (super.noSuchMethod(
        Invocation.method(
          #containsKey,
          [key],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> setBool(
    String? key,
    bool? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setBool,
          [
            key,
            value,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> setInt(
    String? key,
    int? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setInt,
          [
            key,
            value,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> setDouble(
    String? key,
    double? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setDouble,
          [
            key,
            value,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> setString(
    String? key,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setString,
          [
            key,
            value,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> setStringList(
    String? key,
    List<String>? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setStringList,
          [
            key,
            value,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> remove(String? key) => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [key],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> clear({Set<String>? allowList}) => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
          {#allowList: allowList},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
